@startuml
'https://plantuml.com/class-diagram

hide empty members

Hero *- Position : pos
Hero *-- Direction : dir
Hero *-- Walk : walk

class Position{
  row: Int
  col: Int
}

enum Direction{
  DOWN
  LEFT
  RIGHT
  UP
  --
  dRow: Int
  dCol: Int
}

enum Walk {
    STAND
    START
    MID
    END
}
@enduml